Drag and drop
lad-tech/mobydick pull request #128
Opened 2024-03-18 07:15 UTC by vpsmolina

2024-04-04 09:08 UTC, petrovakd commented on packages/dragAndDrop/src/DragAndDrop/DragAndDrop.tsx
> +      const oldOlder = positions.value[id];
здесь наверное oldOrder

2024-04-04 10:04 UTC, vpsmolina commented on packages/dragAndDrop/src/DragAndDrop/DragAndDrop.tsx
> +      const oldOlder = positions.value[id];
спасибо!

2024-04-04 10:55 UTC, petrovakd approved these changes

2024-04-04 11:39 UTC, Bibazavr requested changes

2024-04-04 11:39 UTC, Bibazavr commented on packages/dragAndDrop/src/DragAndDrop/DragAndDrop.tsx
> +    const zIndex = isGestureActive.value ? 100 : 0;
А почему такой zIndex мб меньше его сделать?

2024-04-04 11:39 UTC, Bibazavr commented on packages/dragAndDrop/package.json
> +    "mobydick-chart",
Почему chart?

2024-04-04 11:39 UTC, Bibazavr commented on packages/dragAndDrop/package.json
> +    "chart",
И туть?

2024-04-04 11:39 UTC, Bibazavr commented on packages/dragAndDrop/package.json
> +  "author": "Kirill Lebedev <lebedevki@lad24.ru>",
Ставь себя - это твое детище:)

2024-04-04 11:48 UTC, vpsmolina commented on packages/dragAndDrop/package.json
> +  "author": "Kirill Lebedev <lebedevki@lad24.ru>",
я везде тебя оставляла)))

2024-04-04 11:50 UTC, vpsmolina commented on packages/dragAndDrop/package.json
> +    "mobydick-chart",
потому что копипаст)
Спасибо!

2024-04-04 12:00 UTC, petrovakd approved these changes

2024-04-05 05:26 UTC, Bibazavr approved these changes

2024-04-05 07:26 UTC, merged

2024-04-08 05:50 UTC, Bibazavr commented
:tada: This PR is included in version 7.27.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: