docs(Avatar): added example and docs
lad-tech/mobydick pull request #134
Opened 2024-03-19 14:15 UTC by vpsmolina

close #101

2024-03-20 05:12 UTC, Bibazavr requested changes

2024-03-20 05:12 UTC, Bibazavr commented on packages/core/src/other/components/Avatar/__tests__/AvatarGroup.test.tsx
> +} from '../../../../../../../src/shared/lib/test/data/avatar';
Вот это не очень хорошо - нельзя тестовые данные вне пакета убирать

Лучше их оставить внутри `packages/core`

2024-03-20 05:35 UTC, Deahrunt approved these changes

2024-03-20 05:36 UTC, vpsmolina commented on packages/core/src/other/components/Avatar/__tests__/AvatarGroup.test.tsx
> +} from '../../../../../../../src/shared/lib/test/data/avatar';
точно)

2024-03-20 05:50 UTC, Deahrunt approved these changes

2024-03-20 05:50 UTC, Bibazavr approved these changes
LGTM!

2024-03-20 05:53 UTC, merged

2024-04-02 07:46 UTC, Bibazavr commented
:tada: This PR is included in version 7.26.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: