Docs/168 chart dots
lad-tech/mobydick pull request #177
Opened 2024-03-29 06:37 UTC by vpsmolina

Close #168

2024-03-29 06:42 UTC, Bibazavr requested changes
Наверное, лучше вот так переименовать:о

2024-03-29 06:42 UTC, Bibazavr commented on packages/chart/src/components/PointsOfLine.tsx
> +export const PointsOfLine = ({pointIndex, chartPath}: IPointsProps) => {
```suggestion
export const PointOfLine = ({pointIndex, chartPath}: IPointsProps) => {
```

2024-03-29 06:42 UTC, Bibazavr commented on packages/chart/src/components/Points.tsx
> +export const Points = ({chartPath}: IPointsProps) => {
```suggestion
export const LinePoints = ({chartPath}: IPointsProps) => {
```

2024-03-29 06:51 UTC, Bibazavr approved these changes

2024-03-29 07:37 UTC, Emilien7 approved these changes

2024-03-29 07:44 UTC, MaShikSemenova approved these changes

2024-03-29 07:47 UTC, merged

2024-04-02 07:45 UTC, Bibazavr commented
:tada: This PR is included in version 7.26.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: