docs(api): added docs for useToggle hook
lad-tech/mobydick pull request #183
Opened 2024-03-29 10:34 UTC by Emilien7

Close #122

2024-03-29 10:50 UTC, Deahrunt approved these changes

2024-03-29 10:56 UTC, Bibazavr requested changes

2024-03-29 10:56 UTC, Bibazavr commented on docs/docs/API/utils/useToggle.mdx
> +The `useToggle` React hook useful when value must be `Boolean` type
Что-то странный он, по кабудке он больше не используется нигде - мб выпилим его?

Мы выпили когда-то Toggle, а про этот хук видимо забыли

2024-03-29 11:44 UTC, petrovakd commented on docs/docs/API/utils/useToggle.mdx
> +The `useToggle` React hook useful when value must be `Boolean` type
у нас в Пути Солнца он используется в глазике инпута пароля, мне кажется он полезный

2024-03-29 11:44 UTC, petrovakd approved these changes

2024-04-01 07:10 UTC, Bibazavr approved these changes

2024-04-01 08:56 UTC, merged

2024-04-02 07:44 UTC, Bibazavr commented
:tada: This PR is included in version 7.26.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: