docs(api): added docs for useThrottle hook
lad-tech/mobydick pull request #191
Opened 2024-04-02 06:52 UTC by Emilien7

Close #124

2024-04-02 06:55 UTC, Bibazavr requested changes

2024-04-02 06:55 UTC, Bibazavr commented on docs/docs/API/utils/useThrottle.md
> +import {createStyles, Search, SimpleIcon, useStyles, View} from 'shared/ui';
Тут лучше бы указать @lad-tech/mobydick-core

2024-04-02 06:55 UTC, Bibazavr commented on docs/docs/API/utils/useThrottle.md
> +import {useThrottle} from "shared/mobydick-utils";
И тут

2024-04-02 06:55 UTC, vpsmolina submitted a review, later dismissed

2024-04-02 07:25 UTC, Bibazavr approved these changes

2024-04-02 07:53 UTC, petrovakd approved these changes

2024-04-02 07:53 UTC, merged

2024-04-02 07:53 UTC, vpsmolina approved these changes

2024-04-08 05:50 UTC, Bibazavr commented
:tada: This PR is included in version 7.27.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.27.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: