Markdown
lad-tech/mobydick pull request #224
Opened 2024-04-26 14:01 UTC by petrovakd

2024-04-27 03:20 UTC, Bibazavr approved these changes

2024-04-27 03:21 UTC, Bibazavr requested changes
А почему только в тестовое приложение?

Надо бы новую либу выпустить для этого:о

2024-04-27 05:28 UTC, vpsmolina submitted a review, later dismissed

2024-04-27 06:32 UTC, Bibazavr requested changes

2024-04-27 06:32 UTC, Bibazavr commented on packages/markdown/package.json
> +    "reanimated"
```suggestion
    "markdown"
```

2024-04-27 08:41 UTC, Deahrunt approved these changes

2024-04-27 08:50 UTC, Bibazavr approved these changes

2024-04-27 08:51 UTC, merged

2024-05-02 06:07 UTC, Bibazavr commented
:tada: This PR is included in version 7.31.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-26 08:47 UTC, Bibazavr commented
:tada: This issue has been resolved in version 7.34.0-next.1 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.34.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-08-16 12:51 UTC, Bibazavr commented
:tada: This issue has been resolved in version 7.35.0-next.1 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.35.0-next.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: