Feat modal ref
lad-tech/mobydick pull request #28
Opened 2023-12-06 04:17 UTC by AlexIkonnikov

Added `MobyDickPopup` object and `usePopup` hook.

Profit:
- Calling modal from anywhere in the application, not just from the component;
- There is no need to store modal ID on the client (now this is handled by the library);
- Without breaking changes 😄

2023-12-10 11:31 UTC, Bibazavr requested changes

2023-12-10 11:31 UTC, Bibazavr commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
Это прикольный задел на будущие)

Только думаю, что не стоит нам 2 openPopup держать, я думаю, что мой можно заменить на твой и сильно ничего не должно поменяться:о 

Только в твой надо оставить возможность передавать свой id, если очень хочется:)

2023-12-11 04:05 UTC, AlexIkonnikov commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
Твой удалять нельзя, так как у него в параметрах объект передается. У моего два параметра, первый - это компонент, второй - его пропсы. Могу объединить твой и мой, и добавить if. Выглядеть будет примерно вот так:

```
 const openPopup = (
    param: IOpenPopupParams | Parameters<IModalRef['openPopup']>[0],
    props?: Parameters<IModalRef['openPopup']>[1],
  ) => {
    if (typeof param === 'function') {
      const id = props?.id || (popupId++).toString();
      dispatch(
        openPopupAction({
          Content: param,
          props: props || {},
          id,
        }),
      );
      return id;
    }

    const id = param.id || (popupId++).toString();
    dispatch(
      openPopupAction({
        ...param,
        id,
      }),
    );
    return id;
  };
```
Так нормально будет?

Насчет id - окей, добавлю.

2023-12-11 05:44 UTC, Bibazavr commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
может лучше оба сделать, чтобы получали объект?:о

2023-12-11 06:44 UTC, AlexIkonnikov commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
Хорошо, поправлю

2023-12-11 16:13 UTC, AlexIkonnikov commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
@Bibazavr я поправил, но из-за этого пришлось править типы

Так же, как мне кажется, теперь, при передачи пропсов компонента через новое поле, появляется вложеность (объект внутри объекта), которая возможно будет ухудшать читаемость кода, пример:

```
MobyDickPopup.openPopup({
  Content: Popup,
  props: {
    title: 'Some title',
    discription: 'discription'
    ....
  },
});

```

Так же, что наиболее важно я считаю, у нас пропсы `id` и `overlayStyle` передаются отдельно, хотя если разобраться - это те же пропсы компонента. Это может создать путаницу в будущем:

```
MobyDickPopup.openPopup({
  id: 'some-id', // можно было бы так же сделать частью пропсов
  overlayStyle: {backgroundColor: 'red'}, //можно было бы так же сделать частью пропсов
  Content: Popup,
  props: {
    title: 'Some title',
    discription: 'discription',
  },
});
```

2023-12-11 16:56 UTC, Bibazavr commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
> Так же, как мне кажется, теперь, при передачи пропсов компонента через новое поле, появляется вложеность (объект внутри объекта), которая возможно будет ухудшать читаемость кода, пример:

Спорно, мы можем же раньше определить пропсы, которые будем передавать туда что-то типо:

```ts
const props = {
    title: 'Some title',
    discription: 'discription'
    ....
  }

MobyDickPopup.openPopup({
  Content: Popup,
  props
});
```

( можем обсудить на следующем мобидике:) )

> Так же, что наиболее важно я считаю, у нас пропсы id и overlayStyle передаются отдельно, хотя если разобраться - это те же пропсы компонента. Это может создать путаницу в будущем:

С id не уверен, что он нужен именно в пропсах нам, мне не очень хочется чтобы модальник, что либо знал про id - у него есть функция закрытия и он самодостаточный:)

А вот overlayStyle - это странно, что он туда попал (по кабудке его там не должно быть), он ни как не влияет на открытие модалок сам по себе:о

Вероятно он попал, когда делали разные типы для модалок и этот пропс добавили не туда куда надо:с

@vpsmolina не знаешь зачем он там?:о

2023-12-11 18:21 UTC, Bibazavr submitted a review, later dismissed
LGTM!

2023-12-12 03:28 UTC, AlexIkonnikov commented
> LGTM!

2023-12-12 03:35 UTC, AlexIkonnikov commented on packages/core/src/popups/context/PopupsProvider.tsx
> +        props: ownProps || {},
<img width="975" alt="Снимок экрана 2023-12-12 в 09 29 23" src="https://github.com/lad-tech/mobydick/assets/61405349/6ee68709-9fec-4ab1-8ac8-3eba72d6f9f9">

@Bibazavr поломалась типизация. Правда линтер про это почему-то промолчал. 
Идея была в том, чтобы была возможность передавать компонент как функцию, а не jsx. Это нужно для того, чтобы использовать функционал в файлах, с любым расширением (ts/tsx). То есть при передачи компонента в поле `Content` он получал основные пропсы модалки (id, onClose), а остальное передавалось через props + можно было опционально закинуть свой onClose (для переопределения поведения) и так же id (если очень хочется).

2023-12-13 04:42 UTC, Bibazavr approved these changes

2023-12-13 12:04 UTC, MaShikSemenova approved these changes

2023-12-13 12:12 UTC, merged

2023-12-13 12:15 UTC, Bibazavr commented
:tada: This PR is included in version 7.16.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: