chore: add inputs to demo app
lad-tech/mobydick pull request #69
Opened 2024-02-11 08:18 UTC by AlexIkonnikov

2024-02-12 03:54 UTC, Bibazavr requested changes

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/ExampleSearch.tsx
> +  return StyleSheet.create({
При использовании createStyles, совсем не обязательно использовать StyleSheet.create - автокомплит стилей и так работать будет)

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/Header.tsx
> +  return StyleSheet.create({
При использовании createStyles, совсем не обязательно использовать StyleSheet.create - автокомплит стилей и так работать будет)

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +  return StyleSheet.create({
При использовании createStyles, совсем не обязательно использовать StyleSheet.create - автокомплит стилей и так работать будет)

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/Verification.tsx
> +  return StyleSheet.create({
При использовании createStyles, совсем не обязательно использовать StyleSheet.create - автокомплит стилей и так работать будет)

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
Что-то в темной теме текст темный почему-то - надо бы разобраться:о (смотрел на ios)

2024-02-12 03:54 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
![image](https://github.com/lad-tech/mobydick/assets/51177449/d24d3e6d-3674-4055-9dcc-82436981a936)

2024-02-12 03:59 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
Хотя мб у меня что-то закешировалось...

2024-02-12 04:14 UTC, AlexIkonnikov commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
Замечания по createStyles поправил, а вот с этим пока не ясно, буду чуть позже смотреть, но тут и текст между группами инпутов у тебя тоже пропал, так как он тоже почему-то имеет темный цвет.

2024-02-12 04:38 UTC, AlexIkonnikov commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
@Bibazavr мультилайновый инпут вроде починил, но это все равно не нормально. Тут смотри какая ситуация, если текст имеет черный цвет, то почему-то он не переключается. На экране с typography такая же проблема.

https://github.com/lad-tech/mobydick/assets/61405349/8c104ea3-ac16-4bd9-b4db-9c3fb5f8f293

2024-02-12 04:41 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/InputList.tsx
> +        secureTextEntry={isSecureTextEntry}
@AlexIkonnikov А там в зедере не правильный font используется 

<img width="753" alt="image" src="https://github.com/lad-tech/mobydick/assets/51177449/bbd55be0-899f-4a07-b1da-b589bcae0dd9">


Black - будет всегда черным в любой теме

2024-02-12 04:44 UTC, Bibazavr commented on src/widgets/Core/Inputs/ui/Header.tsx
> +    <Typography font={'Regular-Black-H5'} style={styles.h5}>
```suggestion
    <Typography font={'Regular-Primary-H5'} style={styles.h5}>
```

2024-02-12 04:47 UTC, AlexIkonnikov commented on src/widgets/Core/Inputs/ui/Header.tsx
> +    <Typography font={'Regular-Black-H5'} style={styles.h5}>
Готово

2024-02-12 05:05 UTC, vpsmolina approved these changes

2024-02-12 05:55 UTC, Bibazavr approved these changes
LGTM!

2024-02-12 06:00 UTC, merged

2024-02-13 06:52 UTC, Bibazavr commented
:tada: This PR is included in version 7.22.0 :tada:

The release is available on [GitHub release](https://github.com/lad-tech/mobydick/releases/tag/v7.22.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: